#### 1. Import the numpy package under the name `np`

In [2]:
import numpy as np

#### 2. Create a null array of size 10

In [3]:
np.zeros(10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 3.  Create a null array of size 10 but make the fifth value 1

In [4]:
a = np.zeros(10)
a[4] = 1
a

array([ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

#### 4.  Create an array with values ranging from 10 to 49

In [5]:
np.arange(10,49)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 5.  Reverse an array (first element becomes last)

In [6]:
a = np.arange(1,20)
r = a[::-1]
r

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8

In [7]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Find the indices of non-zero elements from \[2,5,0,0,4,0\]

In [39]:
#[a for a in [2,5,0,0,4,0] if a !=0]
x = np.nonzero([1,2,0,0,4,0])
print(x)

(array([0, 1, 4], dtype=int64),)


#### 8. Create a 3x3x3 array with random values 

In [42]:
np.random.rand(3,3,3)

array([[[ 0.89355066,  0.14783143,  0.84851342],
        [ 0.74622234,  0.75383127,  0.7265176 ],
        [ 0.27029156,  0.32551768,  0.87331887]],

       [[ 0.62336715,  0.43416323,  0.57928299],
        [ 0.83321366,  0.75349576,  0.6384322 ],
        [ 0.45651387,  0.97208793,  0.31394897]],

       [[ 0.72139897,  0.88926897,  0.36001394],
        [ 0.18641532,  0.17237133,  0.93516207],
        [ 0.85446944,  0.81900112,  0.79514767]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values

In [17]:
a = np.random.rand(10,10)
maximum = np.amax(a)
minimum = np.min(a)
print(a)
print(maximum)
print(minimum)

[[ 0.65373951  0.57082487  0.07969373  0.82715512  0.34192144  0.10173329
   0.86568778  0.96140844  0.2087084   0.32976839]
 [ 0.85641424  0.48532376  0.73244679  0.87622208  0.58526523  0.34717574
   0.87056698  0.27225762  0.37878867  0.97463398]
 [ 0.73981538  0.37486949  0.17306471  0.5966581   0.66640197  0.71209834
   0.23431978  0.2208978   0.70526103  0.29527871]
 [ 0.79454137  0.90468542  0.46121836  0.71949222  0.63936674  0.24766736
   0.38905814  0.11235172  0.68950732  0.30841178]
 [ 0.83188583  0.50040068  0.65602997  0.78191929  0.1626371   0.26776566
   0.93789791  0.3599371   0.32227346  0.73638167]
 [ 0.60847656  0.90403176  0.89961806  0.34374158  0.63181581  0.0224218
   0.63714534  0.81194854  0.61142783  0.13557989]
 [ 0.64574038  0.67575721  0.07016341  0.85156352  0.44134349  0.24952589
   0.14531384  0.31054413  0.37243933  0.29005429]
 [ 0.42194876  0.45499542  0.89753122  0.86319947  0.83398242  0.33479304
   0.72095101  0.03800714  0.00759397  0.98161459]
 

#### 10. Create a random array of size 25 and find the mean value

In [19]:
a = np.random.rand(5,5)
print(a)
np.mean(a)

[[ 0.79960746  0.62420855  0.31103195  0.62525226  0.94914346]
 [ 0.41474569  0.74617568  0.06853995  0.61034417  0.85513025]
 [ 0.9003578   0.50016193  0.48954177  0.16265023  0.881192  ]
 [ 0.97893019  0.85004232  0.62246073  0.36540797  0.83746685]
 [ 0.54406314  0.24648162  0.67588484  0.93545869  0.43574828]]


0.61720111091888474

#### 11. Create a 2d array with 1s on the borders and 0s inside

In [21]:
a = np.ones((5,5))
print(a)
a[1:-1,1:-1] = 0
print(a)

[[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]]
[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


#### 12. Normalize a 5x5 random matrix

In [43]:
#I have a few doubts in this questions,Broadcasting
"""a = np.arange(0,100,4).reshape(5,5)
row_sums = a.sum(axis = 1)
new_matrix = np.zeros((5,5))
zipped = zip(a, row_sums)
print(list(zipped))
for i, (row, row_sum) in enumerate(zip(a, row_sums)):
    new_matrix[i,:] = row / row_sum
new_matrix"""

"""a = np.arange(0,100,4).reshape(5,5)
row_sums = a.sum(axis=1)
new_matrix = a / row_sums[:, np.newaxis]
new_matrix"""

Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z = (Z - Zmin)/(Zmax - Zmin)
print(Z)

[[ 0.5026183   0.90964917  0.28603288  0.44031201  0.64277138]
 [ 0.48003606  0.27470061  0.          0.5619654   0.85106612]
 [ 0.49767288  0.57380359  0.54470543  0.4073559   0.99848058]
 [ 0.41803702  0.99786215  0.40564556  0.20015213  0.46741347]
 [ 0.95691765  0.88526273  0.15593893  0.50813939  1.        ]]


#### 13. Create a 5x5 matrix with row values ranging from 5 to 9

In [49]:
x = np.zeros((5,5))
a = x + np.arange(5,10)
print(a)

[[ 5.  6.  7.  8.  9.]
 [ 5.  6.  7.  8.  9.]
 [ 5.  6.  7.  8.  9.]
 [ 5.  6.  7.  8.  9.]
 [ 5.  6.  7.  8.  9.]]


#### 14. Create a random vector of size 12 and sort it

In [51]:
x = np.random.random(12)
print(x)
np.sort(x)

[ 0.99906169  0.53984257  0.41098781  0.27227809  0.44318291  0.48217143
  0.53022354  0.36999107  0.27474674  0.22812538  0.98988644  0.92541196]


array([ 0.22812538,  0.27227809,  0.27474674,  0.36999107,  0.41098781,
        0.44318291,  0.48217143,  0.53022354,  0.53984257,  0.92541196,
        0.98988644,  0.99906169])

#### 15. Swap the first two rows of the following array

In [54]:
#Advanced Indexing
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
